# -*- coding: utf-8 -*-
"""fyers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mFxnEGwEJuLrxj1o3H6rcPIgzs_FQ0Z
"""

import pandas as pd

# Load the datasets (assuming they have been previously loaded)
nse_cm = pd.read_csv('/content/NSE_CM.csv')
bse_fo = pd.read_csv('/content/BSE_FO.csv')
nse_fo = pd.read_csv('/content/NSE_FO.csv')
bse_cm = pd.read_csv('/content/BSE_CM.csv')

# Extract and rename relevant columns
nse_cm_cleaned = nse_cm[
    ['GOLDSTAR POWER LIMITED', 'INE405Y01021', 'NSE:GOLDSTAR-SM']].rename(columns={
    'GOLDSTAR POWER LIMITED': 'Instrument_Name',
    'INE405Y01021': 'ISIN_Code',
    'NSE:GOLDSTAR-SM': 'Ticker_Symbol'
})

bse_fo_cleaned = bse_fo[
    ['SENSEX 24 Oct 25 80500 PE', 'BSE:SENSEX24OCT80500PE', '2024-10-23', '80500.0', 'PE']
].rename(columns={
    'SENSEX 24 Oct 25 80500 PE': 'Instrument_Name',
    'BSE:SENSEX24OCT80500PE': 'Ticker_Symbol',
    '2024-10-23': 'Expiry_Date',
    '80500.0': 'Strike_Price',
    'PE': 'Option_Type'
})

nse_fo_cleaned = nse_fo[
    ['NIFTY 24 Oct 24 20150 CE', 'NSE:NIFTY24O2420150CE', '2024-10-23', '20150.0', 'CE']
].rename(columns={
    'NIFTY 24 Oct 24 20150 CE': 'Instrument_Name',
    'NSE:NIFTY24O2420150CE': 'Ticker_Symbol',
    '2024-10-23': 'Expiry_Date',
    '20150.0': 'Strike_Price',
    'CE': 'Option_Type'
})

bse_cm_cleaned = bse_cm[
    ['SENSEX-INDEX', 'BSE:SENSEX-INDEX']
].rename(columns={
    'SENSEX-INDEX': 'Instrument_Name',
    'BSE:SENSEX-INDEX': 'Ticker_Symbol'
})

# Merge the cleaned datasets
consolidated_fyers_data = pd.concat(
    [nse_cm_cleaned, bse_fo_cleaned, nse_fo_cleaned, bse_cm_cleaned],
    ignore_index=True
)

# Save the consolidated file if needed
consolidated_fyers_data.to_csv('/content/consolidated_fyers_data.csv', index=False)
# Print the first few rows to verify
print(consolidated_fyers_data.head())

consolidated_fyers_data.info()

