# -*- coding: utf-8 -*-
"""Street Partners.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bFP1nlLX33u3xQGzNESRo3wvPuAhcphU
"""

import pandas as pd

# load the CSV files
icici_df = pd.read_csv('/content/ICICI.csv')
zerodha_df = pd.read_csv('/content/zerodha.csv')
fyers_df = pd.read_csv('/content/consolidated_fyers_data.csv')

# seeing the first few rows of each file to understand the structure and there values
print("ICICI Data:\n", icici_df.head())
print("Zerodha Data:\n", zerodha_df.head())
print("Fyers Data:\n", fyers_df.head())

# ICICI: selecting the relevant columns (modify based on actual column names after inspection)
icici_cleaned = icici_df[['SC', 'ISIN', 'EC', 'SG']].copy()
icici_cleaned.columns = ['tradingsymbol', 'ISIN', 'exchange', 'segment']

# Zerodha: Selecting the relevant columns
zerodha_cleaned = zerodha_df[['tradingsymbol', 'exchange', 'segment']].copy()

# Clean the Fyers data
fyers_cleaned = fyers_df[['Ticker_Symbol', 'ISIN_Code']].copy()
fyers_cleaned.columns = ['tradingsymbol', 'ISIN']

# Check the cleaned data
print("ICICI Cleaned:\n", icici_cleaned.head())
print("Zerodha Cleaned:\n", zerodha_cleaned.head())
print("Fyers Cleaned:\n", fyers_cleaned.head())

# Merge ICICI and Zerodha data on 'tradingsymbol'
merged_df = pd.merge(icici_cleaned, zerodha_cleaned, on=['tradingsymbol', 'exchange'], how='outer', suffixes=('_icici', '_zerodha'))

# Merge the result with Fyers data on 'tradingsymbol'
merged_df = pd.merge(merged_df, fyers_cleaned, on=['tradingsymbol'], how='outer', suffixes=('_merged', '_fyers'))

# Check the merged dataframe
print("Merged Data:\n", merged_df.head())

# Export the final merged dataframe to a CSV
merged_df.to_csv('singular_script_mapping.csv', index=False)
print("Singular mapping exported successfully as 'singular_script_mapping.csv'")

merged_df.sample(10)

merged_df.info()

